name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10-dind
        ports:
          - 2375:2375
        options: --privileged

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/2.20.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Start Sail
      run: |
        ./vendor/bin/sail up -d
    - name: Wait for MySQL
      run: |
        until ./vendor/bin/sail exec -T mysql mysqladmin ping -h"localhost" --silent; do
          echo "Waiting for database..."
          sleep 1
        done
    - name: Set Up Database
      run: |
        ./vendor/bin/sail artisan migrate --seed
    - name: Execute tests (Unit and Feature tests)
      run: |
        ./vendor/bin/sail test
