name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10-dind
        ports:
          - 2375:2375
        options: --privileged

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - name: Set up Docker
      run: |
        docker version
        docker-compose version
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Start Docker Compose
      run: |
        docker-compose up -d
    - name: Wait for MySQL
      run: |
        until docker-compose exec -T mysql mysqladmin ping -h"localhost" --silent; do
          echo "Waiting for database..."
          sleep 1
        done
    - name: Set Up Database
      run: |
        docker-compose exec -T laravel.test php artisan migrate --seed
    - name: Execute tests (Unit and Feature tests)
      run: |
        docker-compose exec -T laravel.test ./vendor/bin/sail test
